spring:
  output:
    ansi:
      enabled: always
---
spring:
  profiles: h2
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver

---
spring:
  profiles: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/tutorial?characterEncoding=UTF-8&serverTimezone=UTC
      username: springbatch
      password: springbatch
      driver-class-name: com.mysql.cj.jdbc.Driver
    env:
      sample: 10