sever:
  port: 98080
  tomcat:
      additional-tld-skip-patterns: '*.jar'
spring:
  output:
    ansi:
      enabled: always
  batch:
    job:
      enabled: true
      names: ${job.name:NONE}
  quartz:
    job-store-type: jdbc
    jdbc.initialize-schema: NEVER
    properties:
      org.quartz.scheduler.instanceName: quartz-scheduler-app
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.scheduler.instanceIdGenerator.class: kr.co.agramar.scheduler.CustomQuartzInstanceIdGenerator
      org.quartz.scheduler.skipUpdateCheck: true
      org.quartz.scheduler.jobFactory.class: org.quartz.simpl.SimpleJobFactory
      org.quartz.threadPool.threadCount: 20
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      org.quartz.jobStore.useProperties: true
      org.quartz.jobStore.tablePrefix: qrtz_
      org.quartz.jobStore.isClustered: true
      org.quartz.plugin.shutdownHook.class: org.quartz.plugins.management.ShutdownHookPlugin
      org.quartz.plugin.shutdownHook.cleanShutdown: TRUE
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      generate-ddl: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        default_batch_fetch_size: ${chunkSize:1000}
  main:
    allow-bean-definition-overriding: true
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
mybatis:
  type-aliases-package: kr.co.agramar.entity
  lazy-initialization: true
  mapper-locations: classpath:kr/co/agramar/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 1000
    default-statement-timeout: 30
---
spring:
  profiles:
    active: local
  datasource:
    master:
      jdbc-url: ENC(6SeDQl25tkd85e14+iuf+mVhSJ0NtALxVavcqjuX2NgsFE4pu21gjF5rglZlhJgT1KfnbSuYJM0V3n84/FOohceJzgJ5mtIOa0ph0z9CfZLFz6A8LuMZGQ==)
      username: ENC(MaKsjiW/3TbTFvljwvvNP139YzDepOoh)
      password: ENC(xTCMmaR+pCnwe24xFv/LhfQBWdfU9R92)
      poolName: HikariPool-Master
      readOnly: false
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 1
      maximum-pool-size: 10
      idle-timeout: 10000
      connection-timeout: 20000
      max-lifetime: 2000000
    slave:
      jdbc-url: ENC(aomN5aZJH+8kegUUEUgqDxTSI5e4eUhbCYpmUJY3lDxOGieQgvJtjpukH/xWgk9nQYhF0jBPi1iddx6rbjR8K/XYju3g+2p76INcGsyCRqNySVwP+pdvlA==)
      username: ENC(Z4NFn1jYF1QpstbsQt90/X6eeWPsJs96)
      password: ENC(pWWCGpYxbQkVmEgjWllZEzt/4UlUdpUX)
      poolName: HikariPool-Slave
      readOnly: true
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 10000
      connection-timeout: 20000
      max-lifetime: 2000000
logging:
  level:
    org.springframework.batch: DEBUG
    com.zaxxer: DEBUG